# Generated by Django 3.1.4 on 2020-12-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_auto_20201221_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(default='product.png', upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(error_messages={'required': 'Quantity must be provided'})),
                ('unit', models.CharField(choices=[('kilograms', 'KILOGRAMS'), ('litres', 'LITRES')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('sell_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenden.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(error_messages={'required': 'Quantity must be provided'})),
                ('unit', models.CharField(blank=True, choices=[('kilograms', 'KILOGRAMS'), ('litres', 'LITRES')], default='', max_length=10, null=True)),
                ('imported_from', models.CharField(max_length=200)),
                ('customs_clearance_no', models.PositiveBigIntegerField(error_messages={'unique': 'A user with that email already exists.'}, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('import_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenden.product')),
            ],
        ),
    ]
