# Generated by Django 3.1.4 on 2020-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='pending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
