# Generated by Django 3.1.4 on 2020-12-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201218_2139'),
        ('lenden', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='Product',
        ),
    ]
