# Generated by Django 3.1.4 on 2020-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
