# Generated by Django 3.1.4 on 2020-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenden', '0002_auto_20201228_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalan',
            name='customs_clearance_no',
            field=models.PositiveBigIntegerField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, null=True, unique=True),
        ),
    ]
