# Generated by Django 3.1.4 on 2021-01-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenden', '0002_auto_20210106_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
