# Generated by Django 3.1.4 on 2020-12-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenden', '0003_auto_20201227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
