# Generated by Django 3.1.4 on 2020-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trade_license_no',
            field=models.PositiveBigIntegerField(error_messages={'unique': 'A user with that trade license is already exists.'}, null=True, unique=True),
        ),
    ]
