# Generated by Django 3.1.4 on 2020-12-14 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201214_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signed_up',
            field=models.DateField(default=datetime.date(2020, 12, 14)),
        ),
    ]
