# Generated by Django 3.1.4 on 2020-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_signed_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('importer', 'Importer'), ('wholeseller', 'Whole Seller')], error_messages={'required': 'Role must be provided'}, max_length=15),
        ),
    ]
