# Generated by Django 3.1.4 on 2020-12-14 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201214_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signed_up',
            field=models.DateField(default=datetime.date(2020, 12, 15)),
        ),
    ]
