# Generated by Django 3.1.4 on 2020-12-17 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201215_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signed_up',
            field=models.DateField(default=datetime.date(2020, 12, 17)),
        ),
    ]
