# Generated by Django 3.1.4 on 2020-12-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201217_1625'),
        ('accounts', '0007_auto_20201218_1137'),
    ]

    operations = [
    ]
