# Generated by Django 3.1.4 on 2020-12-21 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201219_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='signed_up',
            field=models.DateField(default=datetime.date(2020, 12, 21)),
        ),
    ]
