# Generated by Django 3.1.4 on 2021-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('warning', 'WARNING'), ('fine', 'FINE'), ('info', 'INFO'), ('order', 'ORDER')], default='info', max_length=34),
        ),
    ]
